export default [
    [
        {
            "id": 1,
            "weight": 1,
            "type": "simple",
            "price": 10, 
            "occupied": false,
            "raw": 1,
            "line": 2,
        },
        {
            "id": 2,
            "weight": 1,
            "type": "simple",
            "price": 10, 
            "occupied": false,
            "raw": 1,
            "line": 2,
        },
        {
            "id": 3,
            "weight": 1,
            "type": "simple",
            "price": 10, 
            "occupied": false,
            "raw": 1,
            "line": 2,
        },
        {
            "id": 4,
            "weight": 1,
            "type": "simple",
            "price": 10, 
            "occupied": false,
            "raw": 1,
            "line": 2,
        },
        {
            "id": 11,
            "weight": 1,
            "type": "comfort",
            "price": 20, 
            "occupied": false,
            "raw": 1,
            "line": 2,
        },
    ],
    [
        {
            "id": 5,
            "weight": 1,
            "type": "simple",
            "price": 10, 
            "occupied": false,
            "raw": 1,
            "line": 2,
        },
        {
            "id": 6,
            "weight": 1,
            "type": "simple",
            "price": 10, 
            "occupied": false,
            "raw": 1,
            "line": 2,
        },
        {
            "id": 7,
            "weight": 1,
            "type": "simple",
            "price": 10, 
            "occupied": false,
            "raw": 1,
            "line": 2,
        },
        {
            "id": 11,
            "weight": 1,
            "type": "comfort",
            "price": 20, 
            "occupied": false,
            "raw": 1,
            "line": 2,
        },
        {
            "id": 11,
            "weight": 1,
            "type": "comfort",
            "price": 20, 
            "occupied": false,
            "raw": 1,
            "line": 2,
        },
    ],
    [
        {
            "id": 8,
            "weight": 1,
            "type": "simple",
            "price": 10, 
            "occupied": false,
            "raw": 1,
            "line": 2,
        },
        {
            "id": 11,
            "weight": 2,
            "type": "loveseat",
            "price": 20, 
            "occupied": false,
            "raw": 1,
            "line": 2,
        },

        {
            "id": 11,
            "weight": 2,
            "type": "loveseat",
            "price": 20, 
            "occupied": false,
            "raw": 1,
            "line": 2,
        },
    ]

]