export default [
    {
        "filmName": "avatar",
        "seatType": "loveseats",
        "price": 20,
        "raw": 1,
        "line": 2,
    },
    {
        "filmName": "avatar",
        "seatType": "standard",
        "price": 10,
        "raw": 1,
        "line": 2,
    },
    {
        "filmName": "avatar",
        "seatType": "comfort",
        "price": 20,
        "raw": 1,
        "line": 2,
    },
    {
        "filmName": "avatar",
        "seatType": "loveseats",
        "price": 20,
        "raw": 1,
        "line": 2,
    },
    {
        "filmName": "avatar",
        "seatType": "standard",
        "price": 10,
        "raw": 1,
        "line": 2,
    },
    {
        "filmName": "avatar",
        "seatType": "comfort",
        "price": 20,
        "raw": 1,
        "line": 2,
    },
    {
        "filmName": "avatar",
        "seatType": "loveseats",
        "price": 20,
        "raw": 1,
        "line": 2,
    },
    {
        "filmName": "avatar",
        "seatType": "standard",
        "price": 10,
        "raw": 1,
        "line": 2,
    },
    {
        "filmName": "avatar",
        "seatType": "comfort",
        "price": 20,
        "raw": 1,
        "line": 2,
    },
    {
        "filmName": "avatar",
        "seatType": "loveseats",
        "price": 20,
        "raw": 1,
        "line": 2,
    },
    {
        "filmName": "avatar",
        "seatType": "standard",
        "price": 10,
        "raw": 1,
        "line": 2,
    },
    {
        "filmName": "avatar",
        "seatType": "comfort",
        "price": 20,
        "raw": 1,
        "line": 2,
    },
]