export default [
    [
        {
            id: 1,
            type: "standard",
            price: 10, 
            occupied: false,
            raw: 1,
            line: 2,
        },
        {
            id: 2,
            type: "standard",
            price: 10, 
            occupied: false,
            raw: 1,
            line: 2,
        },
        {
            id: 3,
            type: "standard",
            price: 10, 
            occupied: false,
            raw: 1,
            line: 2,
        },
        {
            id: 4,
            type: "standard",
            price: 10, 
            occupied: false,
            raw: 1,
            line: 2,
        },
        {
            id: 11,
            type: "comfort",
            price: 20, 
            occupied: false,
            raw: 1,
            line: 2,
        },
    ],
    [
        {
            id: 5,
            type: "standard",
            price: 10, 
            occupied: false,
            raw: 1,
            line: 2,
        },
        {
            id: 6,
            type: "standard",
            price: 10, 
            occupied: false,
            raw: 1,
            line: 2,
        },
        {
            id: 7,
            type: "standard",
            price: 10, 
            occupied: false,
            raw: 1,
            line: 2,
        },
        {
            id: 11,
            type: "comfort",
            price: 20, 
            occupied: false,
            raw: 1,
            line: 2,
        },
        {
            id: 11,
            type: "comfort",
            price: 20, 
            occupied: false,
            raw: 1,
            line: 2,
        },
    ],
    [
        {
            id: 8,
            type: "standard",
            price: 10, 
            occupied: false,
            raw: 1,
            line: 2,
        },
        {
            id: 11,
            type: "loveseat",
            price: 20, 
            occupied: false,
            raw: 1,
            line: 2,
        },

        {
            id: 11,
            type: "loveseat",
            price: 20, 
            occupied: false,
            raw: 1,
            line: 2, 
        },
    ]

]